### ISSUE TITLE
Small typo in the `README.md` file

### ISSUE THREAD

**Issue by amir-jakoby** [he1nh/openshift-prometheus#1]
Hi,
I have been following the readme and found a small typo in the section that describes how to retrieve the password for the `haproxy` statistics page:
```
oc export dc route | grep -A1 STATS_PASSWORD
```

should be
```
oc export dc router | grep -A1 STATS_PASSWORD
```

Emphasize on the route that should be route**r**

Thanks for the guide and project BTW!!

**Comment by he1nh** [comment]
Hi Amir,

I've updated the README.md. Thanks for calling it in.

Kind Regards, Hein
